### ISSUE TITLE
Add a timeout command

### ISSUE THREAD

**Issue by Costpap** [Costpap/CostBot#468]
**Is your feature request related to a problem? Please describe.**

Currently, the bot has no command that utilizes Discord's recent [Time Out feature](https://support.discord.com/hc/en-us/articles/4413305239191). This means that in any servers utilizing CostBot, if mods want to time out a member, they're unable to do so using the bot and have to either resort to using another bot or doing it through the UI. 

**Describe the solution you'd like**

Implement a `timeout` command. The command would be split into two subcommands, one of them being `add` and the other being `remove`.

The `add` subcommand would first check the member's permissions, since members with the `ADMINISTRATOR` permission, as well as server owners, cannot be timed out. Afterwards, it would time out the user, and depending on the options supplied, inform them of the duration & reason for the time out, based on the options provided by the moderator. 

The `remove` subcommand would simply allow moderators to remove any ongoing timeouts.

**Describe alternatives you've considered**

There are no alternative solutions, other than not implementing the feature at all.

**Additional context**

**Comment by Ladam0203** [comment]
Hey! I'd love to work on this! Can you please add me as a participant? Or should I just raise a PR?

**Comment by Costpap** [comment]
Hi there! Feel free to open a pull  request when you've finished working on the feature. I'll be sure to review & merge it. 

I've already started working on the command myself but haven't been able to finish it, if you want to I can send you a gist of the code I've got so far later.

**Comment by Ladam0203** [comment]
Sure, thank you! I am already setting up things, based on how you have done it in your other files to ensure consistency...

**Comment by Costpap** [comment]
Sounds good! I'll send the gist here whenever I go home.

**Comment by Ladam0203** [comment]
I have finished the command, I'll wait for your gist to see what you were on, take that into account and I'll open a PR. C:
